
export const COMPREHENSIVE_SPORTS = [
  { label: "Padel", value: "padel" },
  { label: "Tennis", value: "tennis" },
  { label: "Badminton", value: "badminton" },
  { label: "Pickleball", value: "pickleball" },
  { label: "Squash", value: "squash" },
  { label: "Table Tennis", value: "table-tennis" },
  { label: "Basketball", value: "basketball" },
  { label: "Volleyball", value: "volleyball" },
  { label: "Football (Soccer)", value: "football" },
  { label: "American Football", value: "american-football" },
  { label: "Baseball", value: "baseball" },
  { label: "Golf", value: "golf" },
  { label: "Cricket", value: "cricket" },
  { label: "Rugby", value: "ruby" },
  { label: "Handball", value: "handball" },
  { label: "Hockey", value: "hockey" },
  { label: "Ice Hockey", value: "ice-hockey" },
  { label: "Swimming", value: "swimming" },
  { label: "Athletics", value: "athletics" },
  { label: "MMA", value: "mma" },
  { label: "Boxing", value: "boxing" },
  { label: "Chess", value: "chess" },
  { label: "E-Sports", value: "e-sports" },
];
